### ISSUE TITLE
Button Action: Deleting Action can't be saved

### ISSUE THREAD

**Issue by deinhofer** [asterics/FABI#32]
Deleting a keyboard action can't be saved.

![grafik](https://user-images.githubusercontent.com/4621810/146189474-ca485aba-55f8-4c39-ab27-6663f320d9ae.png)

Generally a global "Delete action" button could make sense here:

![grafik](https://user-images.githubusercontent.com/4621810/146189991-ba0efba8-813c-4c8d-b19b-4d276ed6ea6c.png)

**Comment by ChrisVeigl** [comment]
i do not understand the problem, as "Delete" shall only remove assigned keystrokes (which works IMO correctly)...

should a "Delete Action" Button assign the "no command" action  (which currently is only available in the "Device/Gerät"-Tab? - this would indeed make it easier...

**Comment by klues** [comment]
I could add a button "Delete Action", but when it's really needed?
If (a) the user can trigger this input action, then you normally would define some action for it or if (b) the user cannot trigger this input action, it's also not necessary to delete the action...

**Comment by deinhofer** [comment]
> i do not understand the problem, as "Delete" shall only remove assigned keystrokes (which works IMO correctly)...
> 
> should a "Delete Action" Button assign the "no command" action (which currently is only available in the "Device/Gerät"-Tab? - this would indeed make it easier...

But I think that's the point. First I did not realize that the "Delete" was only for deleting the keystroke field contents. I thought that I could unassign an action to this input, but this was not the case. Then I accidently recognzied that it's possible to unset an action but only in the  "Alle Kategorien" tab. I think this is not obvious.

Maybe it would even be better to directly add a delete action (waste bin icon) directly to the action list.
![grafik](https://user-images.githubusercontent.com/4621810/146827512-23baf6e8-3c21-457e-902f-b452f2324b13.png)

**Comment by ChrisVeigl** [comment]
i see!
i agree that this is a bit unintuitive!
(also that an unassigned action is called "no command" / "keine Aktion" in the All/Device tabs, but "empty"/"leer" in the action list!  - here, the same wording should be used!  

A seperate button for the "AT NC" command could indeed make sense, replacing the entries in the All/Device menus. We could call it "No Action"/"Keine Aktion" and in the list "no action"/keine Aktion" could be displayed ?

**Comment by klues** [comment]
I've now changed it to `No command (empty) // Keine Funktion (leer)` in the combobox in order to better match the wording displayed in the table. I think `empty // leer` is better in the table because it's short and therefore better visible separated from other entries.

Yes, I can add a `Clear command` button, but I'm not so sure where. I can do it like @deinhofer suggested, but to my mind this is a little bit to prominent compared to the importance (like said: how often this button really will be used?!). Additionally all the buttons at the bottom are closing the modal, while for the `Clear command` button it maybe would make more sense if it just sets the current AT-command to "No command" which then can be saved (if needed also for all slots) using the existing buttons. My suggestion would be a little wastebin icon at one of these places: https://i.imgur.com/SCuUIUd.png

**Comment by ChrisVeigl** [comment]
the wastebin icon sounds like a good idea.
i think i'd prefer the location in the combobox.

**Comment by klues** [comment]
Now implemented it like this: https://i.imgur.com/kQ3wEc3.png
It's already online, tell me, what you think.
